### ISSUE TITLE
MacOS Example

### ISSUE THREAD

**Issue by CyrosX** [norepimorphism/boing#8]
Hello!

I've used the [control_gallery.rs](https://github.com/norepimorphism/boing/blob/main/boing/examples/control_gallery.rs) to make these screenshots. Data Choosers is somehow empty.
<img width="473" alt="basic-controls" src="https://user-images.githubusercontent.com/15161462/218130294-dac10726-91a7-44d0-9acf-4a8072eab2a0.png">
<img width="474" alt="data-choosers" src="https://user-images.githubusercontent.com/15161462/218130301-da0320bc-439b-417a-8bae-d78d89af6eb0.png">
<img width="473" alt="numbers-and-lists" src="https://user-images.githubusercontent.com/15161462/218130305-c88b7f9b-0507-440e-9beb-20ae547e2af1.png">

**Comment by norepimorphism** [comment]
Thanks so much! I'll add these to the README later today.

> Data Choosers is somehow empty.

That is expected. The font and color pickers are currently disabled (and are not publicly exported by the crate) because they are unsound and crash the program. I haven't gotten around to making a GitHub issue yet.

**Comment by norepimorphism** [comment]
Fixed in #c1d7a6f.
